name: catalog-api-test-build-artifacts

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install packages, Run build, Test app
        run: |
          npm install
          npm run build --if-present
          npm test
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
            name: catalog-api-artifact
            path: |
              ./app.js
              ./node_modules/
              ./routes/
              ./spec/
              ./package.json
              ./package-lock.json
              

    
          
