name: docker-build

on:
  workflow_dispatch:

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCES_TOKEN}}
    - name: Build and push to docker hub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: szychasz007/catalog-api-build-on-github:latest, szychasz007/catalog-api-build-on-github:${{github.run_number}}
